description: learn your rights and organize for better living conditions
baseurl: /
title: Tenants Rights
email: alexn@tenantsunion.org

# build settings
markdown: CommonMark
theme: minima

commonmark:
  options: ["FOOTNOTES", "SMART"]
  extensions: ["strikethrough", "autolink", "table", "tasklist", "tagfilter"]
