title: Tenants Rights
author:
  name:  Alex N
  email: alexn@tenantsunion.org
  phone: +12534331647
description: > # this means to ignore newlines until "show_excerpts:"
  learn your rights and organize for better living conditions

show_excerpts: false # set to true to show excerpts on the homepage

# build settings
markdown: CommonMark
theme: minima

minima:
  skin: solarized
  social_links:
    twitter: TenantsUnionWa
    facebook: TenantsUnion

commonmark:
  options: ["FOOTNOTES", "SMART"]
  extensions: ["strikethrough", "autolink", "table", "tasklist", "tagfilter"]
